### ISSUE TITLE
License Section in Table of Contents

### ISSUE THREAD

**Issue by mdclyburn** [clemsonacm/hackpack#27]
It should be immediately obvious where the licenses are and it would be a boon if they showed up in the table of contents, but they don't. Can this be worked in?

**Comment by robertu94** [comment]
I was aware of this issue, and  I will look for a way to fix it.  I think the best that we will be able to do is to make an Appendix section and make the Licenses a chapter of that section.

It has to deal with how we import the licenses into the Hackpack.  The licenses have to be conveyed verbatim as they are distributed from gnu.org.  So I didn't want to edit the TeX that they serve as the license to get it to work as part of a larger document as opposed to as standalone as GNU distributes it.
